- name: db server
  hosts: [db]
  become: yes
  vars:
   login_host: db.devopsm26.online
  tasks:
     - name: Install mysql
       ansible.builtin.dnf:
         name: mysql-server
         state: latest

     - name: Start and Enable MySQL server
       ansible.builtin.service:
         name: mysqld
         state: started
         enabled: yes
     - name: check db passord
       community.mysql.mysql_info:
          login_user: root
          login_password: ExpenseApp@1
          login_host: "{{ login_host }}"
          filter: version
       ignore_errors: yes
       register: mysql_connection_output

     - name: output
       ansible.builtin.debug:
        msg: "output: {{ mysql_connection_output }}"
